# Laravel cPanel Auto-Deployment
# ------------------------------
# 1. Simpan file ini di root folder project Anda.
# 2. Sesuaikan DEPLOYPATH dengan lokasi folder public_html Anda.
# 3. Jalankan 'git commit' & 'git push' ke repo Git Anda.
# 4. Tekan tombol 'Deploy' di menu Git Version Control cPanel.

---
deployment:
  tasks:
    # Target folder di cPanel (disesuaikan dengan username Anda: tococoi1)
    - export DEPLOYPATH=/home/tococoi1/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/rm $DEPLOYPATH/.cpanel.yml
